--- #YAML:1.0
name:               HTTP-LoadGen
version:            0.07
abstract:           a HTTP load generator toolset
author:
    - Torsten Förtsch <torsten.foertsch@gmx.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:          5.261
    Async::Interrupt:  1.05
    Coro:              5.23
    IPC::ScoreBoard:   0.03
    Net::SSLeay:       1.35
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
