--- #YAML:1.0
name:                HTTP-LoadGen
version:             0.03
abstract:            a HTTP load generator toolset
license:             ~
author:              
    - Torsten Förtsch <torsten.foertsch@gmx.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    AnyEvent:                      5.261
    Async::Interrupt:              1.05
    Coro:                          5.23
    IPC::ScoreBoard:               0.03
    Net::SSLeay:                   1.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
